<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: audit/security-events.latte */
final class Template_639162e2af extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['event' => '11'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="rounded-xl border border-white/10 bg-white/5 p-4 mb-4">
    <h3 class="font-semibold">Security Events</h3>
</div>
<div class="rounded-xl border border-white/10 bg-white/5 overflow-auto">
    <table class="w-full text-sm">
        <thead class="bg-white/5"><tr><th class="px-3 py-2 text-left">Action</th><th class="px-3 py-2 text-left">User</th><th class="px-3 py-2 text-left">Time</th></tr></thead>
        <tbody>
';
		foreach ($events as $event) /* pos 11:9 */ {
			echo '            <tr class="border-t border-white/10"><td class="px-3 py-2">';
			echo LR\HtmlHelpers::escapeText($event['action'] ?? '-') /* pos 12:72 */;
			echo '</td><td class="px-3 py-2">';
			echo LR\HtmlHelpers::escapeText($event['user_id'] ?? '-') /* pos 12:124 */;
			echo '</td><td class="px-3 py-2">';
			echo LR\HtmlHelpers::escapeText($event['timestamp'] ?? '-') /* pos 12:177 */;
			echo '</td></tr>
';

		}

		echo '        </tbody>
    </table>
</div>
';
	}
}
