<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: audit/index.latte */
final class Template_e498643dc4 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '16', 'event' => '27'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
    <div class="rounded-xl border border-white/10 bg-white/5 p-4"><p class="text-xs text-gray-400">Today</p><p class="text-2xl font-semibold">';
		echo LR\HtmlHelpers::escapeText($summary['today_activity'] ?? 0) /* pos 5:143 */;
		echo '</p></div>
    <div class="rounded-xl border border-white/10 bg-white/5 p-4"><p class="text-xs text-gray-400">Week</p><p class="text-2xl font-semibold">';
		echo LR\HtmlHelpers::escapeText($summary['week_activity'] ?? 0) /* pos 6:142 */;
		echo '</p></div>
    <div class="rounded-xl border border-white/10 bg-white/5 p-4"><p class="text-xs text-gray-400">Users Today</p><p class="text-2xl font-semibold">';
		echo LR\HtmlHelpers::escapeText($summary['unique_users_today'] ?? 0) /* pos 7:149 */;
		echo '</p></div>
    <div class="rounded-xl border border-white/10 bg-white/5 p-4"><p class="text-xs text-gray-400">Security Events</p><p class="text-2xl font-semibold">';
		echo LR\HtmlHelpers::escapeText($summary['security_events_today'] ?? 0) /* pos 8:153 */;
		echo '</p></div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <section class="rounded-xl border border-white/10 bg-white/5 p-4">
        <div class="flex items-center justify-between mb-3"><h3 class="font-semibold">Top Actions</h3><a class="text-sm text-blue-400" href="/audit/system-activity">Details</a></div>
';
		if (empty($topActions)) /* pos 14:9 */ {
			echo '        <p class="text-sm text-gray-400">No data.</p>';
		} else /* pos 14:77 */ {
			echo '
            <div class="space-y-2">
';
			foreach ($topActions as $item) /* pos 16:17 */ {
				echo '                    <div class="flex items-center justify-between rounded-lg border border-white/10 px-3 py-2"><span>';
				echo LR\HtmlHelpers::escapeText($item['action'] ?? '-') /* pos 17:118 */;
				echo '</span><span class="text-gray-300">';
				echo LR\HtmlHelpers::escapeText($item['count'] ?? 0) /* pos 17:177 */;
				echo '</span></div>
';

			}

			echo '            </div>
';
		}
		echo '    </section>

    <section class="rounded-xl border border-white/10 bg-white/5 p-4">
        <div class="flex items-center justify-between mb-3"><h3 class="font-semibold">Security Events</h3><a class="text-sm text-blue-400" href="/audit/security-events">Details</a></div>
';
		if (empty($securityEvents)) /* pos 25:9 */ {
			echo '        <p class="text-sm text-gray-400">No data.</p>';
		} else /* pos 25:81 */ {
			echo '
            <div class="space-y-2">
';
			foreach ($securityEvents as $event) /* pos 27:17 */ {
				echo '                    <div class="rounded-lg border border-white/10 px-3 py-2">
                        <p class="text-sm font-medium">';
				echo LR\HtmlHelpers::escapeText($event['action'] ?? '-') /* pos 29:56 */;
				echo '</p>
                        <p class="text-xs text-gray-400">';
				echo LR\HtmlHelpers::escapeText($event['timestamp'] ?? '-') /* pos 30:58 */;
				echo '</p>
                    </div>
';

			}

			echo '            </div>
';
		}
		echo '    </section>
</div>
';
	}
}
