<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: auth/login.latte */
final class Template_af53a28618 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/auth.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="mb-6">
    <h2 class="text-2xl font-bold mb-2">Sign In</h2>
    <p class="text-slate-400 text-sm">Masuk ke akun admin Anda</p>
</div>

<form class="space-y-5" method="post" action="/login">
    ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 10:5 */;
		echo '
    <div>
        <label class="block text-sm font-medium mb-2 text-slate-300">Email Address</label>
        <div class="relative">
            <i data-lucide="mail" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400"></i>
            <input type="email" name="email" placeholder="admin@bangrondb.local" class="w-full pl-12 pr-4 py-3 rounded-xl bg-slate-700/50 border border-slate-600 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500" required>
        </div>
    </div>

    <div>
        <label class="block text-sm font-medium mb-2 text-slate-300">Password</label>
        <div class="relative">
            <i data-lucide="lock" class="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5 text-slate-400"></i>
            <input type="password" name="password" placeholder="********" class="w-full pl-12 pr-4 py-3 rounded-xl bg-slate-700/50 border border-slate-600 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500" required>
        </div>
    </div>

    <button type="submit" class="w-full py-3.5 bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 rounded-xl font-semibold transition-all">Sign In</button>
</form>
';
	}
}
