<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: collections/settings.latte */
final class Template_86b681b343 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
		echo "\n";
		$this->renderBlock('scripts', get_defined_vars()) /* pos 116:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['field' => '48, 64'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="max-w-4xl space-y-4">
    <div class="rounded-xl border border-white/10 bg-white/5 p-4">
        <h3 class="font-semibold mb-1">Collection Settings</h3>
        <p class="text-sm text-gray-400">';
		echo LR\HtmlHelpers::escapeText($dbName) /* pos 7:42 */;
		echo ' / ';
		echo LR\HtmlHelpers::escapeText($collection) /* pos 7:54 */;
		echo '</p>
    </div>

    <form method="post" action="/collections/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 10:46 */;
		echo '/settings" class="space-y-4">
        ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 11:9 */;
		echo '
        <input type="hidden" name="db"';
		echo LR\HtmlHelpers::formatAttribute(' value', $dbName) /* pos 12:48 */;
		echo '>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 rounded-xl border border-white/10 bg-white/5 p-4">
            <div>
                <label class="text-sm">ID Mode</label>
                <select name="id_mode" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                    <option value="auto" ';
		if (($config['id_mode'] ?? 'auto') === 'auto') /* pos 18:42 */ {
			echo 'selected';
		}
		echo '>auto</option>
                    <option value="manual" ';
		if (($config['id_mode'] ?? '') === 'manual') /* pos 19:44 */ {
			echo 'selected';
		}
		echo '>manual</option>
                    <option value="prefix" ';
		if (($config['id_mode'] ?? '') === 'prefix') /* pos 20:44 */ {
			echo 'selected';
		}
		echo '>prefix</option>
                </select>
            </div>
            <div>
                <label class="text-sm">ID Prefix</label>
                <input name="id_prefix"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['id_prefix'] ?? 'ID') /* pos 25:49 */;
		echo ' class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
            </div>
            <label class="flex items-center gap-2 text-sm">
                <input type="checkbox" name="encryption_enabled" value="1" ';
		if (!empty($config['encryption_enabled'])) /* pos 28:76 */ {
			echo 'checked';
		}
		echo '>
                Encryption Enabled
            </label>
            <label class="flex items-center gap-2 text-sm">
                <input type="checkbox" name="soft_deletes_enabled" value="1" ';
		if (!empty($config['soft_deletes_enabled'])) /* pos 32:78 */ {
			echo 'checked';
		}
		echo '>
                Soft Deletes Enabled
            </label>
            <div class="md:col-span-2">
                <label class="text-sm">Deleted At Field</label>
                <input name="deleted_at_field"';
		echo LR\HtmlHelpers::formatAttribute(' value', $config['deleted_at_field'] ?? '_deleted_at') /* pos 37:56 */;
		echo ' class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
            </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 rounded-xl border border-white/10 bg-white/5 p-4">
            <div>
                <label class="text-sm">Searchable Fields</label>
                <div class="mt-2 max-h-56 overflow-auto rounded-lg border border-white/10 bg-black/20 p-3 space-y-2">
';
		if (empty($schemaFields)) /* pos 45:21 */ {
			echo '                        <p class="text-xs text-gray-400">No schema fields. Define fields in Schema Builder first.</p>
';
		} else /* pos 47:21 */ {
			foreach ($schemaFields as $field) /* pos 48:25 */ {
				echo '                            <label class="flex items-center gap-2 text-sm">
                                <input type="checkbox" name="searchable_fields[]"';
				echo LR\HtmlHelpers::formatAttribute(' value', $field['name']) /* pos 50:91 */;
				echo ' ';
				if (in_array($field['name'], $searchableList ?? [], true)) /* pos 50:108 */ {
					echo 'checked';
				}
				echo '>
                                <span>';
				echo LR\HtmlHelpers::escapeText($field['name']) /* pos 51:39 */;
				echo '</span>
                                <span class="text-xs text-gray-500">(';
				echo LR\HtmlHelpers::escapeText($field['type']) /* pos 52:70 */;
				echo ')</span>
                            </label>
';

			}

		}
		echo '                </div>
            </div>
            <div>
                <label class="text-sm">Encrypted Fields</label>
                <div class="mt-2 max-h-56 overflow-auto rounded-lg border border-white/10 bg-black/20 p-3 space-y-2">
';
		if (empty($schemaFields)) /* pos 61:21 */ {
			echo '                        <p class="text-xs text-gray-400">No schema fields.</p>
';
		} else /* pos 63:21 */ {
			foreach ($schemaFields as $field) /* pos 64:25 */ {
				echo '                            <label class="flex items-center gap-2 text-sm">
                                <input type="checkbox" name="encrypted_fields[]"';
				echo LR\HtmlHelpers::formatAttribute(' value', $field['name']) /* pos 66:90 */;
				echo ' ';
				if (in_array($field['name'], $encryptedList ?? [], true)) /* pos 66:107 */ {
					echo 'checked';
				}
				echo '>
                                <span>';
				echo LR\HtmlHelpers::escapeText($field['name']) /* pos 67:39 */;
				echo '</span>
                                <span class="text-xs text-gray-500">(';
				echo LR\HtmlHelpers::escapeText($field['type']) /* pos 68:70 */;
				echo ')</span>
                            </label>
';

			}

		}
		echo '                </div>
            </div>
            <div class="md:col-span-2">
                <label class="text-sm">Indexes (comma separated)</label>
                <input type="hidden" id="indexesCsv" name="indexes_csv"';
		echo LR\HtmlHelpers::formatAttribute(' value', implode(', ', $indexList ?? [])) /* pos 76:82 */;
		echo '>
                <div class="mt-1 rounded-lg border border-white/10 bg-white/5 p-2">
                    <div id="indexTags" class="mb-2 flex flex-wrap gap-2"></div>
                    <div class="flex gap-2">
                        <input id="indexTagInput" class="w-full rounded-lg border border-white/10 bg-black/20 px-3 py-2 text-sm" placeholder="Ketik field index lalu Enter, contoh: email">
                        <button type="button" id="addIndexTagBtn" class="rounded-lg border border-white/20 px-3 py-2 text-sm hover:bg-white/10">Add</button>
                    </div>
                    <p class="mt-2 text-xs text-gray-500">Tip: tekan `Enter` atau klik `Add` untuk menambah index.</p>
                </div>
            </div>
        </div>

        <div class="rounded-xl border border-white/10 bg-white/5 p-4">
            <details>
                <summary class="cursor-pointer text-sm font-medium">Advanced JSON (optional override)</summary>
                <div class="mt-3 space-y-3">
                    <div>
                        <label class="text-sm">Schema JSON</label>
                        <textarea name="schema_json" rows="6" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono">';
		echo LR\HtmlHelpers::escapeText(json_encode($config['schema'] ?? [], 128)) /* pos 94:156 */;
		echo '</textarea>
                    </div>
                    <div>
                        <label class="text-sm">Indexes JSON</label>
                        <textarea name="indexes_json" rows="4" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono">';
		echo LR\HtmlHelpers::escapeText(json_encode($config['indexes'] ?? [], 128)) /* pos 98:157 */;
		echo '</textarea>
                    </div>
                    <div>
                        <label class="text-sm">Custom Config JSON</label>
                        <textarea name="custom_json" rows="4" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono">';
		echo LR\HtmlHelpers::escapeText(json_encode($config['custom_config'] ?? [], 128)) /* pos 102:156 */;
		echo '</textarea>
                    </div>
                </div>
            </details>
        </div>

        <div class="flex gap-2">
            <button class="rounded-lg bg-blue-600 hover:bg-blue-700 px-4 py-2 text-sm">Save Settings</button>
            <a href="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 110:33 */;
		echo '?db=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 110:61 */;
		echo '" class="rounded-lg border border-white/20 px-4 py-2 text-sm hover:bg-white/10">Back</a>
        </div>
    </form>
</div>
';
	}


	/** {block scripts} on line 116 */
	public function blockScripts(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<script>
(() => {
    const hidden = document.getElementById(\'indexesCsv\');
    const tagsContainer = document.getElementById(\'indexTags\');
    const input = document.getElementById(\'indexTagInput\');
    const addBtn = document.getElementById(\'addIndexTagBtn\');
    if (!hidden || !tagsContainer || !input || !addBtn) return;

    let tags = (hidden.value || \'\')
        .split(\',\')
        .map((x) => x.trim())
        .filter((x) => x.length > 0);

    const normalize = (v) => v.trim().replace(/\\s+/g, \'_\');

    function syncHidden() {
        hidden.value = tags.join(\', \');
    }

    function render() {
        tagsContainer.innerHTML = \'\';
        if (!tags.length) {
            const empty = document.createElement(\'span\');
            empty.className = \'text-xs text-gray-500\';
            empty.textContent = \'Belum ada index.\';
            tagsContainer.appendChild(empty);
            syncHidden();
            return;
        }

        tags.forEach((tag) => {
            const chip = document.createElement(\'span\');
            chip.className = \'inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-blue-500/10 px-3 py-1 text-xs text-blue-200\';
            chip.innerHTML = `<span>${escapeHtml(tag)}</span><button type="button" data-remove="${escapeAttr(tag)}" class="text-blue-300 hover:text-white">×</button>`;
            tagsContainer.appendChild(chip);
        });
        syncHidden();
    }

    function addTag(raw) {
        const value = normalize(raw);
        if (!value) return;
        const valid = /^[A-Za-z0-9_.]+$/;
        if (!valid.test(value)) {
            return;
        }
        if (!tags.includes(value)) {
            tags.push(value);
        }
        input.value = \'\';
        render();
    }

    function removeTag(value) {
        tags = tags.filter((x) => x !== value);
        render();
    }

    function escapeHtml(text) {
        return String(text)
            .replaceAll(\'&\', \'&amp;\')
            .replaceAll(\'<\', \'&lt;\')
            .replaceAll(\'>\', \'&gt;\')
            .replaceAll(\'"\', \'&quot;\')
            .replaceAll("\'", \'&#039;\');
    }

    function escapeAttr(text) {
        return escapeHtml(text);
    }

    addBtn.addEventListener(\'click\', () => addTag(input.value));
    input.addEventListener(\'keydown\', (e) => {
        if (e.key === \'Enter\') {
            e.preventDefault();
            addTag(input.value);
        }
    });
    tagsContainer.addEventListener(\'click\', (e) => {
        const btn = e.target.closest(\'[data-remove]\');
        if (!btn) return;
        removeTag(btn.getAttribute(\'data-remove\') || \'\');
    });

    render();
})();
</script>
';
	}
}
