<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: dashboard/index.latte */
final class Template_5822d5517e extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['row' => '55', 'log' => '132'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4 mb-6">
    <div class="glass-card rounded-xl p-6 stat-card">
        <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 bg-blue-500/20 rounded-xl flex items-center justify-center"><i data-lucide="database" class="w-6 h-6 text-blue-400"></i></div>
            <span class="text-sm text-green-400">Live</span>
        </div>
        <h3 class="text-3xl font-bold mb-1">';
		echo LR\HtmlHelpers::escapeText(count($databases)) /* pos 10:45 */;
		echo '</h3>
        <p class="text-gray-400 text-sm">Total Databases</p>
    </div>

    <div class="glass-card rounded-xl p-6 stat-card">
        <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 bg-purple-500/20 rounded-xl flex items-center justify-center"><i data-lucide="folder" class="w-6 h-6 text-purple-400"></i></div>
            <span class="text-sm text-green-400">Live</span>
        </div>
        <h3 class="text-3xl font-bold mb-1">';
		echo LR\HtmlHelpers::escapeText($totalCollections) /* pos 19:45 */;
		echo '</h3>
        <p class="text-gray-400 text-sm">Total Collections</p>
    </div>

    <div class="glass-card rounded-xl p-6 stat-card">
        <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 bg-green-500/20 rounded-xl flex items-center justify-center"><i data-lucide="file-json" class="w-6 h-6 text-green-400"></i></div>
            <span class="text-sm text-green-400">Live</span>
        </div>
        <h3 class="text-3xl font-bold mb-1">';
		echo LR\HtmlHelpers::escapeText($totalDocuments ?? 0) /* pos 28:45 */;
		echo '</h3>
        <p class="text-gray-400 text-sm">Total Documents</p>
    </div>

    <div class="glass-card rounded-xl p-6 stat-card">
        <div class="flex items-center justify-between mb-4">
            <div class="w-12 h-12 bg-yellow-500/20 rounded-xl flex items-center justify-center"><i data-lucide="users" class="w-6 h-6 text-yellow-400"></i></div>
            <span class="text-sm text-green-400">Active</span>
        </div>
        <h3 class="text-3xl font-bold mb-1">';
		echo LR\HtmlHelpers::escapeText($activeUsers ?? 0) /* pos 37:45 */;
		echo '</h3>
        <p class="text-gray-400 text-sm">Active Users</p>
    </div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
    <section class="lg:col-span-2 glass-card rounded-xl overflow-hidden">
        <div class="p-5 border-b border-white/10 flex items-center justify-between">
            <div>
                <h3 class="font-semibold text-lg">Database Overview</h3>
                <p class="text-sm text-gray-400">Storage usage per database</p>
            </div>
            <a href="/databases" class="text-blue-400 hover:text-blue-300 text-sm">View All</a>
        </div>
        <div class="p-5 space-y-4">
';
		if (empty($databaseOverview)) /* pos 52:13 */ {
			echo '                <p class="text-sm text-gray-400">Belum ada database.</p>
';
		} else /* pos 54:13 */ {
			foreach ($databaseOverview as $row) /* pos 55:17 */ {
				echo '                    <div class="p-4 bg-white/5 rounded-xl">
                        <div class="flex items-center justify-between mb-3">
                            <div class="flex items-center gap-3">
                                <div class="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center">
                                    <i data-lucide="database" class="w-5 h-5 text-blue-400"></i>
                                </div>
                                <div>
                                    <a href="/databases/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($row['name'])) /* pos 63:57 */;
				echo '" class="font-medium hover:text-blue-300">';
				echo LR\HtmlHelpers::escapeText($row['label']) /* pos 63:124 */;
				echo '</a>
                                    <p class="text-sm text-gray-400">';
				echo LR\HtmlHelpers::escapeText($row['collections']) /* pos 64:70 */;
				echo ' collections • ';
				echo LR\HtmlHelpers::escapeText($row['documents']) /* pos 64:108 */;
				echo ' docs</p>
                                </div>
                            </div>
                            <div class="text-right">
                                <p class="font-medium">';
				echo LR\HtmlHelpers::escapeText($row['size_human']) /* pos 68:56 */;
				echo '</p>
                                <p class="text-xs text-gray-400">of 5 GB</p>
                            </div>
                        </div>
                        <div class="h-1.5 rounded bg-white/10 overflow-hidden">
                            <div class="h-full bg-gradient-to-r from-blue-500 to-purple-500 rounded" style="width: ';
				echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($row['usage_percent'])) /* pos 73:116 */;
				echo '%"></div>
                        </div>
                    </div>
';

			}

		}
		echo '        </div>
    </section>

    <section class="glass-card rounded-xl overflow-hidden">
        <div class="p-5 border-b border-white/10">
            <h3 class="font-semibold text-lg">System Health</h3>
            <p class="text-sm text-gray-400">Server status</p>
        </div>
        <div class="p-5 space-y-5">
            <div>
                <div class="flex items-center justify-between mb-2">
                    <span class="text-sm text-gray-400">CPU Usage</span>
                    <span class="text-sm font-medium text-green-400">';
		echo LR\HtmlHelpers::escapeText($systemHealth['cpu_pct'] ?? 0) /* pos 90:70 */;
		echo '%</span>
                </div>
                <div class="h-1.5 rounded bg-white/10 overflow-hidden"><div class="h-full bg-green-500" style="width: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($systemHealth['cpu_pct'] ?? 0)) /* pos 92:119 */;
		echo '%"></div></div>
            </div>
            <div>
                <div class="flex items-center justify-between mb-2">
                    <span class="text-sm text-gray-400">Memory</span>
                    <span class="text-sm font-medium text-yellow-400">';
		echo LR\HtmlHelpers::escapeText($systemHealth['memory_pct'] ?? 0) /* pos 97:71 */;
		echo '%</span>
                </div>
                <div class="h-1.5 rounded bg-white/10 overflow-hidden"><div class="h-full bg-yellow-500" style="width: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($systemHealth['memory_pct'] ?? 0)) /* pos 99:120 */;
		echo '%"></div></div>
                <p class="mt-1 text-xs text-gray-500">';
		echo LR\HtmlHelpers::escapeText($systemHealth['memory_usage_human'] ?? '0 B') /* pos 100:55 */;
		echo ' / ';
		echo LR\HtmlHelpers::escapeText($systemHealth['memory_limit_human'] ?? 'unlimited') /* pos 100:104 */;
		echo '</p>
            </div>
            <div>
                <div class="flex items-center justify-between mb-2">
                    <span class="text-sm text-gray-400">Disk Space</span>
                    <span class="text-sm font-medium text-blue-400">';
		echo LR\HtmlHelpers::escapeText($systemHealth['disk_pct'] ?? 0) /* pos 105:69 */;
		echo '%</span>
                </div>
                <div class="h-1.5 rounded bg-white/10 overflow-hidden"><div class="h-full bg-blue-500" style="width: ';
		echo LR\HtmlHelpers::escapeAttr(LR\Helpers::escapeCss($systemHealth['disk_pct'] ?? 0)) /* pos 107:118 */;
		echo '%"></div></div>
            </div>

            <div class="pt-4 border-t border-white/10 space-y-3">
                <div class="flex items-center justify-between"><div class="flex items-center gap-2"><span class="w-2 h-2 bg-green-500 rounded-full"></span><span class="text-sm">Database Server</span></div><span class="text-xs text-green-400">Healthy</span></div>
                <div class="flex items-center justify-between"><div class="flex items-center gap-2"><span class="w-2 h-2 bg-green-500 rounded-full"></span><span class="text-sm">Auth Service</span></div><span class="text-xs text-green-400">Active</span></div>
                <div class="flex items-center justify-between"><div class="flex items-center gap-2"><span class="w-2 h-2 bg-green-500 rounded-full"></span><span class="text-sm">Backup Service</span></div><span class="text-xs text-green-400">Running</span></div>
            </div>
        </div>
    </section>
</div>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <section class="glass-card rounded-xl overflow-hidden">
        <div class="p-5 border-b border-white/10 flex items-center justify-between">
            <div>
                <h3 class="font-semibold text-lg">Recent Activity</h3>
                <p class="text-sm text-gray-400">Latest operations</p>
            </div>
            <a href="/audit" class="text-blue-400 hover:text-blue-300 text-sm">View All</a>
        </div>
        <div class="divide-y divide-white/5">
';
		if (empty($recentLogs)) /* pos 129:13 */ {
			echo '                <div class="p-4 text-sm text-gray-400">No activity yet.</div>
';
		} else /* pos 131:13 */ {
			foreach ($recentLogs as $log) /* pos 132:17 */ {
				echo '                    <div class="p-4 flex items-start gap-3">
                        <div class="w-9 h-9 bg-blue-500/20 rounded-lg flex items-center justify-center flex-shrink-0"><i data-lucide="activity" class="w-4 h-4 text-blue-400"></i></div>
                        <div class="flex-1 min-w-0">
                            <p class="text-sm font-medium">';
				echo LR\HtmlHelpers::escapeText($log['action'] ?? '-') /* pos 136:60 */;
				echo '</p>
                            <p class="text-xs text-gray-400 mt-1">';
				echo LR\HtmlHelpers::escapeText($log['timestamp'] ?? $log['created_at'] ?? '-') /* pos 137:67 */;
				echo '</p>
                        </div>
                    </div>
';

			}

		}
		echo '        </div>
    </section>

    <div class="space-y-6">
        <section class="glass-card rounded-xl p-5">
            <div class="flex items-center justify-between mb-4">
                <h3 class="font-semibold">Query Statistics</h3>
                <a href="/monitoring" class="text-blue-400 hover:text-blue-300 text-sm">Details</a>
            </div>
            <div class="grid grid-cols-3 gap-4">
                <div class="text-center p-3 bg-white/5 rounded-xl"><p class="text-2xl font-bold text-green-400">';
		echo LR\HtmlHelpers::escapeText($queryStats['read_ops'] ?? 0) /* pos 152:113 */;
		echo '</p><p class="text-xs text-gray-400 mt-1">Read Ops</p></div>
                <div class="text-center p-3 bg-white/5 rounded-xl"><p class="text-2xl font-bold text-blue-400">';
		echo LR\HtmlHelpers::escapeText($queryStats['write_ops'] ?? 0) /* pos 153:112 */;
		echo '</p><p class="text-xs text-gray-400 mt-1">Write Ops</p></div>
                <div class="text-center p-3 bg-white/5 rounded-xl"><p class="text-2xl font-bold text-purple-400">';
		echo LR\HtmlHelpers::escapeText($queryStats['avg_latency'] ?? 'n/a') /* pos 154:114 */;
		echo '</p><p class="text-xs text-gray-400 mt-1">Avg Latency</p></div>
            </div>
        </section>

        <section class="glass-card rounded-xl p-5">
            <div class="flex items-center justify-between mb-4">
                <h3 class="font-semibold">Encryption Status</h3>
                <a href="/security" class="text-blue-400 hover:text-blue-300 text-sm">Manage</a>
            </div>
            <div class="space-y-3">
';
		if (!empty($encryptionStatus['enabled'])) /* pos 164:17 */ {
			echo '                    <div class="flex items-center justify-between p-3 bg-green-500/10 rounded-xl border border-green-500/20"><div class="flex items-center gap-3"><i data-lucide="shield-check" class="w-5 h-5 text-green-400"></i><span class="text-sm">Encryption Key Configured</span></div><span class="text-xs text-green-400 font-medium">SECURE</span></div>
';
		} else /* pos 166:17 */ {
			echo '                    <div class="flex items-center justify-between p-3 bg-yellow-500/10 rounded-xl border border-yellow-500/20"><div class="flex items-center gap-3"><i data-lucide="shield-alert" class="w-5 h-5 text-yellow-400"></i><span class="text-sm">Encryption Key Not Set</span></div><span class="text-xs text-yellow-400 font-medium">WARNING</span></div>
';
		}
		echo '                <div class="flex items-center justify-between p-3 bg-white/5 rounded-xl"><span class="text-sm text-gray-400">Encrypted Collections</span><span class="text-sm font-medium">';
		echo LR\HtmlHelpers::escapeText($encryptionStatus['encrypted_collections'] ?? 0) /* pos 169:188 */;
		echo ' / ';
		echo LR\HtmlHelpers::escapeText($encryptionStatus['total_collections'] ?? 0) /* pos 169:240 */;
		echo '</span></div>
            </div>
        </section>

        <section class="glass-card rounded-xl p-5">
            <h3 class="font-semibold mb-4">Quick Actions</h3>
            <div class="grid grid-cols-2 gap-3">
                <a href="/databases" class="flex flex-col items-center gap-2 p-4 bg-white/5 hover:bg-white/10 rounded-xl transition-colors"><i data-lucide="plus-circle" class="w-6 h-6 text-blue-400"></i><span class="text-sm">New Database</span></a>
                <a href="/databases" class="flex flex-col items-center gap-2 p-4 bg-white/5 hover:bg-white/10 rounded-xl transition-colors"><i data-lucide="folder-plus" class="w-6 h-6 text-purple-400"></i><span class="text-sm">New Collection</span></a>
                <a href="/users" class="flex flex-col items-center gap-2 p-4 bg-white/5 hover:bg-white/10 rounded-xl transition-colors"><i data-lucide="user-plus" class="w-6 h-6 text-green-400"></i><span class="text-sm">Invite User</span></a>
                <a href="/query-playground" class="flex flex-col items-center gap-2 p-4 bg-white/5 hover:bg-white/10 rounded-xl transition-colors"><i data-lucide="terminal" class="w-6 h-6 text-yellow-400"></i><span class="text-sm">Run Query</span></a>
            </div>
        </section>
    </div>
</div>
';
	}
}
