<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: databases/show.latte */
final class Template_81dc3652b8 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['collection' => '19'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="mb-6 flex items-center justify-between">
    <div>
        <h3 class="text-xl font-semibold">';
		echo LR\HtmlHelpers::escapeText($db['_id']) /* pos 6:43 */;
		echo '</h3>
        <p class="text-sm text-gray-400">';
		echo LR\HtmlHelpers::escapeText($db['label'] ?? $db['_id']) /* pos 7:42 */;
		echo '</p>
    </div>
    <a href="/databases/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 9:25 */;
		echo '/settings" class="rounded-lg bg-blue-600 px-3 py-2 text-sm">Database Settings</a>
</div>

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <section class="lg:col-span-2 glass-card rounded-xl overflow-hidden">
        <div class="p-4 border-b border-white/10 flex items-center justify-between"><h4 class="font-semibold">Collections</h4><span class="text-xs text-gray-400">';
		echo LR\HtmlHelpers::escapeText(count($collections)) /* pos 14:163 */;
		echo ' items</span></div>
        <div class="p-4 space-y-2">
';
		if (empty($collections)) /* pos 16:13 */ {
			echo '                <p class="text-sm text-gray-400">No collections.</p>
';
		} else /* pos 18:13 */ {
			foreach ($collections as $collection) /* pos 19:17 */ {
				echo '                    <div class="rounded-lg border border-white/10 px-3 py-2 flex items-center justify-between">
                        <a href="/documents/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 21:45 */;
				echo '?db=';
				echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 21:73 */;
				echo '" class="font-mono text-sm text-blue-400 hover:text-blue-300">';
				echo LR\HtmlHelpers::escapeText($collection) /* pos 21:158 */;
				echo '</a>
                        <a href="/collections/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 22:47 */;
				echo '/settings?db=';
				echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 22:84 */;
				echo '" class="text-xs text-purple-300">Configure</a>
                    </div>
';

			}

		}
		echo '        </div>
    </section>

    <section class="glass-card rounded-xl p-4 space-y-4">
        <div>
            <h4 class="font-semibold mb-2">Create Collection</h4>
            <form method="post" action="/collections/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 32:54 */;
		echo '/create" class="space-y-2">
                ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 33:17 */;
		echo '
                <input name="collection_name" required class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="collection_name">
                <button class="rounded-lg bg-blue-600 px-3 py-2 text-sm">Create</button>
            </form>
        </div>

        <div>
            <h4 class="font-semibold mb-2">Rename</h4>
            <form method="post" action="/collections/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 41:54 */;
		echo '/rename" class="space-y-2">
                ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 42:17 */;
		echo '
                <input name="current_name" required class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="current">
                <input name="new_name" required class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="new">
                <button class="rounded-lg border border-white/20 px-3 py-2 text-sm">Rename</button>
            </form>
        </div>

        <div>
            <h4 class="font-semibold mb-2 text-red-300">Drop</h4>
            <form method="post" action="/collections/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 51:54 */;
		echo '/drop" class="space-y-2">
                ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 52:17 */;
		echo '
                <input name="collection_name" required class="w-full rounded-lg border border-red-500/40 bg-red-500/10 px-3 py-2 text-sm" placeholder="collection_to_drop">
                <button class="rounded-lg bg-red-600 px-3 py-2 text-sm">Drop</button>
            </form>
        </div>
    </section>
</div>
';
	}
}
