<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: databases/settings.latte */
final class Template_c6d0ab89eb extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['issue' => '29', 'backup' => '51'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <section class="rounded-xl border border-white/10 bg-white/5 p-4">
        <h3 class="font-semibold mb-3">Metadata</h3>
        <form method="post" action="/databases/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 7:48 */;
		echo '/settings" class="space-y-3">
            ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 8:13 */;
		echo '
            <div>
                <label class="text-sm">Label</label>
                <input name="label"';
		echo LR\HtmlHelpers::formatAttribute(' value', $db['label'] ?? $db['_id']) /* pos 11:45 */;
		echo ' class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
            </div>
            <div>
                <label class="text-sm">Status</label>
                <select name="status" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                    <option value="active" ';
		if (($db['status'] ?? 'active') === 'active') /* pos 16:44 */ {
			echo 'selected';
		}
		echo '>active</option>
                    <option value="disabled" ';
		if (($db['status'] ?? '') === 'disabled') /* pos 17:46 */ {
			echo 'selected';
		}
		echo '>disabled</option>
                </select>
            </div>
            <button class="rounded-lg bg-blue-600 hover:bg-blue-700 px-4 py-2 text-sm">Save</button>
        </form>
    </section>

    <section class="rounded-xl border border-white/10 bg-white/5 p-4">
        <h3 class="font-semibold mb-3">Health</h3>
        <p class="text-sm">Status: <span class="font-medium">';
		echo LR\HtmlHelpers::escapeText($health['status'] ?? 'unknown') /* pos 26:62 */;
		echo '</span></p>
';
		if (!empty($health['issues'])) /* pos 27:9 */ {
			echo '            <div class="mt-3 space-y-1">
';
			foreach ($health['issues'] as $issue) /* pos 29:17 */ {
				echo '                    <p class="text-xs text-red-300">- ';
				echo LR\HtmlHelpers::escapeText($issue) /* pos 30:55 */;
				echo '</p>
';

			}

			echo '            </div>
';
		}
		echo '
        <div class="mt-5 border-t border-white/10 pt-4">
            <h4 class="font-semibold mb-2">Backup</h4>
            <form method="post" action="/databases/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 37:52 */;
		echo '/backup" class="mb-3">
                ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 38:17 */;
		echo '
                <button class="rounded-lg border border-white/20 px-3 py-2 text-sm hover:bg-white/10">Create Backup</button>
            </form>
            <form method="post" action="/databases/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 41:52 */;
		echo '/backup/prune" class="mb-3 flex items-center gap-2">
                ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 42:17 */;
		echo '
                <input type="number" name="keep_latest" min="1" value="10" class="w-24 rounded-lg border border-white/10 bg-white/5 px-2 py-1 text-sm">
                <button class="rounded-lg border border-white/20 px-3 py-2 text-sm hover:bg-white/10">Prune</button>
            </form>

';
		if (empty($backups)) /* pos 47:13 */ {
			echo '                <p class="text-sm text-gray-400">Belum ada backup.</p>
';
		} else /* pos 49:13 */ {
			echo '                <div class="space-y-2">
';
			foreach ($backups as $backup) /* pos 51:21 */ {
				echo '                        <form method="post" action="/databases/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 52:64 */;
				echo '/restore" class="flex items-center justify-between rounded-lg border border-white/10 px-3 py-2">
                            ';
				echo ($this->global->fn->csrf_field)($this, ) /* pos 53:29 */;
				echo '
                            <input type="hidden" name="backup_id"';
				echo LR\HtmlHelpers::formatAttribute(' value', $backup['_id'] ?? '') /* pos 54:75 */;
				echo '>
                            <div>
                                <p class="text-sm font-mono">';
				echo LR\HtmlHelpers::escapeText($backup['_id'] ?? '-') /* pos 56:62 */;
				echo '</p>
                                <p class="text-xs text-gray-400">';
				echo LR\HtmlHelpers::escapeText($backup['created_at'] ?? '-') /* pos 57:66 */;
				echo '</p>
                            </div>
                            <button class="text-xs rounded-lg bg-emerald-600 px-2 py-1">Restore</button>
                        </form>
';

			}

			echo '                </div>
';
		}
		echo '        </div>
    </section>
</div>
';
	}
}
