<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: databases/index.latte */
final class Template_c530cb6b3f extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['db' => '23'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="flex items-center justify-between mb-6">
    <h3 class="text-lg font-semibold">Databases</h3>
    <button onclick="document.getElementById(\'createDb\').classList.toggle(\'hidden\')" class="rounded-lg bg-blue-600 hover:bg-blue-700 px-4 py-2 text-sm">Create Database</button>
</div>

<div id="createDb" class="hidden glass-card rounded-xl p-4 mb-6">
    <form method="post" action="/databases/create" class="grid grid-cols-1 md:grid-cols-3 gap-3">
        ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 11:9 */;
		echo '
        <input name="name" required class="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="database_name">
        <input name="label" class="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="Label">
        <input name="owner_email" class="rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="Owner email (optional)">
        <button class="md:col-span-3 rounded-lg bg-blue-600 px-4 py-2 text-sm">Create</button>
    </form>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">
';
		if (empty($databases)) /* pos 20:5 */ {
			echo '        <p class="text-sm text-gray-400">Belum ada database.</p>
';
		} else /* pos 22:5 */ {
			foreach ($databases as $db) /* pos 23:9 */ {
				echo '            <article class="glass-card rounded-xl p-4">
                <div class="flex items-start justify-between mb-2">
                    <h4 class="font-mono text-sm">';
				echo LR\HtmlHelpers::escapeText($db['_id']) /* pos 26:51 */;
				echo '</h4>
                    <span class="text-xs px-2 py-1 rounded-md bg-emerald-500/20 text-emerald-300">';
				echo LR\HtmlHelpers::escapeText($db['status'] ?? 'active') /* pos 27:99 */;
				echo '</span>
                </div>
                <p class="text-sm text-gray-400 mb-4">';
				echo LR\HtmlHelpers::escapeText($db['label'] ?? $db['_id']) /* pos 29:55 */;
				echo '</p>
                <div class="flex gap-2">
                    <a href="/databases/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 31:41 */;
				echo '" class="rounded-lg border border-white/20 px-3 py-2 text-xs hover:bg-white/10">Open</a>
                    <a href="/databases/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($db['_id'])) /* pos 32:41 */;
				echo '/settings" class="rounded-lg border border-white/20 px-3 py-2 text-xs hover:bg-white/10">Settings</a>
                </div>
            </article>
';

			}

		}
		echo '</div>
';
	}
}
