<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: documents/index.latte */
final class Template_a5e9986f9f extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
		echo "\n";
		$this->renderBlock('scripts', get_defined_vars()) /* pos 209:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['field' => '76, 91, 152', 'doc' => '88', 'opt' => '164'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="space-y-4">
    <div class="flex items-center justify-between">
        <div>
            <h3 class="text-lg font-semibold">Documents: ';
		echo LR\HtmlHelpers::escapeText($collection) /* pos 7:58 */;
		echo '</h3>
            <p class="text-sm text-gray-400">Database: ';
		echo LR\HtmlHelpers::escapeText($dbName) /* pos 8:56 */;
		echo '</p>
        </div>
        <div class="flex gap-2">
            <a href="/collections/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 11:35 */;
		echo '/settings?db=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 11:72 */;
		echo '" class="rounded-lg border border-white/20 px-3 py-2 text-sm hover:bg-white/10">Collection Settings</a>
            <a href="/databases/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 12:33 */;
		echo '" class="rounded-lg border border-white/20 px-3 py-2 text-sm hover:bg-white/10">Back</a>
        </div>
    </div>

    <form method="get" action="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 16:43 */;
		echo '" class="rounded-xl border border-white/10 bg-white/5 p-4 grid grid-cols-1 md:grid-cols-5 gap-3">
        <input type="hidden" name="db"';
		echo LR\HtmlHelpers::formatAttribute(' value', $dbName) /* pos 17:48 */;
		echo '>
        <div class="md:col-span-2">
            <label class="text-xs text-gray-400">Filter JSON</label>
            <input name="query_json"';
		echo LR\HtmlHelpers::formatAttribute(' value', $queryJson ?? '') /* pos 20:46 */;
		echo ' class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm font-mono" placeholder=\'{"field":"value"}\'>
        </div>
        <div>
            <label class="text-xs text-gray-400">Status</label>
            <select name="status" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                <option value="active" ';
		if (($status ?? 'active') === 'active') /* pos 25:40 */ {
			echo 'selected';
		}
		echo '>active</option>
                <option value="all" ';
		if (($status ?? '') === 'all') /* pos 26:37 */ {
			echo 'selected';
		}
		echo '>all</option>
                <option value="deleted" ';
		if (($status ?? '') === 'deleted') /* pos 27:41 */ {
			echo 'selected';
		}
		echo '>deleted</option>
            </select>
        </div>
        <div>
            <label class="text-xs text-gray-400">Sort</label>
            <select name="sort" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                <option value="_id_desc" ';
		if (($sort ?? '_id_desc') === '_id_desc') /* pos 33:42 */ {
			echo 'selected';
		}
		echo '>_id desc</option>
                <option value="_id_asc" ';
		if (($sort ?? '') === '_id_asc') /* pos 34:41 */ {
			echo 'selected';
		}
		echo '>_id asc</option>
                <option value="created_desc" ';
		if (($sort ?? '') === 'created_desc') /* pos 35:46 */ {
			echo 'selected';
		}
		echo '>created desc</option>
                <option value="created_asc" ';
		if (($sort ?? '') === 'created_asc') /* pos 36:45 */ {
			echo 'selected';
		}
		echo '>created asc</option>
            </select>
        </div>
        <div>
            <label class="text-xs text-gray-400">Limit</label>
            <input type="number" min="1" max="100" name="limit"';
		echo LR\HtmlHelpers::formatAttribute(' value', $limit) /* pos 41:73 */;
		echo ' class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
        </div>
        <div class="md:col-span-5 flex gap-2">
            <button class="rounded-lg bg-blue-600 px-4 py-2 text-sm">Apply</button>
            <a href="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 45:33 */;
		echo '?db=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 45:61 */;
		echo '" class="rounded-lg border border-white/20 px-4 py-2 text-sm hover:bg-white/10">Reset</a>
            <a href="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 46:33 */;
		echo '/export?db=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 46:68 */;
		echo '&status=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($status ?? 'active')) /* pos 46:96 */;
		echo '&sort=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($sort ?? '_id_desc')) /* pos 46:134 */;
		echo '&query_json=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($queryJson ?? '')) /* pos 46:178 */;
		echo '" class="rounded-lg border border-white/20 px-4 py-2 text-sm hover:bg-white/10">Export JSON</a>
        </div>
    </form>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <section class="rounded-xl border border-white/10 bg-white/5 p-4">
            <h4 class="font-semibold mb-2">Create Document</h4>
            <p class="text-sm text-gray-400 mb-3">Gunakan modal schema form agar input lebih rapi.</p>
            <button type="button" id="openCreateModal" class="rounded-lg bg-emerald-600 px-3 py-2 text-sm">Open Schema Form</button>
        </section>
        <section class="rounded-xl border border-white/10 bg-white/5 p-4">
            <h4 class="font-semibold mb-2">Import JSON</h4>
            <form method="post" action="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 58:52 */;
		echo '/import" enctype="multipart/form-data" class="space-y-2">
                ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 59:17 */;
		echo '
                <input type="hidden" name="db"';
		echo LR\HtmlHelpers::formatAttribute(' value', $dbName) /* pos 60:56 */;
		echo '>
                <label class="flex items-center gap-2 text-sm"><input type="checkbox" name="upsert" value="1" checked> upsert by _id</label>
                <input type="file" name="documents_file" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                <textarea name="documents_json" rows="5" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono" placeholder=\'[{"_id":"1","name":"A"}]\'></textarea>
                <button class="rounded-lg border border-white/20 px-3 py-2 text-sm hover:bg-white/10">Import</button>
            </form>
        </section>
    </div>

    <section class="rounded-xl border border-white/10 bg-white/5 overflow-hidden">
        <div class="px-4 py-3 border-b border-white/10 text-sm text-gray-300">Total: ';
		echo LR\HtmlHelpers::escapeText($total) /* pos 70:86 */;
		echo ' documents</div>
        <div class="overflow-auto">
            <table class="w-full min-w-[1100px] text-left text-sm">
                <thead class="bg-white/5 text-gray-300">
                    <tr>
                        <th class="px-4 py-3">_id</th>
';
		foreach ($displayFields as $field) /* pos 76:25 */ {
			echo '                            <th class="px-4 py-3">';
			echo LR\HtmlHelpers::escapeText($field['name']) /* pos 77:51 */;
			echo '</th>
';

		}

		echo '                        <th class="px-4 py-3">Created</th>
                        <th class="px-4 py-3">Updated</th>
                        <th class="px-4 py-3 w-56">Actions</th>
                    </tr>
                </thead>
                <tbody>
';
		if (empty($documents)) /* pos 85:21 */ {
			echo '                        <tr><td class="px-4 py-4 text-gray-400"';
			echo LR\HtmlHelpers::formatAttribute(' colspan', count($displayFields) + 4) /* pos 86:75 */;
			echo '>Tidak ada data.</td></tr>
';
		} else /* pos 87:21 */ {
			foreach ($documents as $doc) /* pos 88:25 */ {
				echo '                            <tr class="border-t border-white/10 align-top">
                                <td class="px-4 py-3 font-mono text-xs">';
				echo LR\HtmlHelpers::escapeText($doc['_id'] ?? '-') /* pos 90:73 */;
				echo '</td>
';
				foreach ($displayFields as $field) /* pos 91:33 */ {
					$cell = $doc[$field['name']] ?? null /* pos 92:37 */;
					echo '                                    <td class="px-4 py-3 text-xs text-gray-200">
';
					if (is_array($cell)) /* pos 94:41 */ {
						echo '                                            <pre class="max-h-24 overflow-auto whitespace-pre-wrap break-all text-xs">';
						echo LR\HtmlHelpers::escapeText(json_encode($cell, 128)) /* pos 95:119 */;
						echo '</pre>
';
					} elseif ($cell === null || $cell === '') /* pos 96:41 */ {
						echo '                                            <span class="text-gray-500">-</span>
';
					} else /* pos 98:41 */ {
						echo '                                            ';
						echo LR\HtmlHelpers::escapeText($cell) /* pos 99:45 */;
						echo "\n";
					}

					echo '                                    </td>
';

				}

				echo '                                <td class="px-4 py-3 text-xs text-gray-300">';
				if (!empty($doc['created_at'])) /* pos 103:77 */ {
					echo LR\HtmlHelpers::escapeText($doc['created_at']) /* pos 103:108 */;
				} else /* pos 103:128 */ {
					echo '-';
				}
				echo '</td>
                                <td class="px-4 py-3 text-xs text-gray-300">';
				if (!empty($doc['updated_at'])) /* pos 104:77 */ {
					echo LR\HtmlHelpers::escapeText($doc['updated_at']) /* pos 104:108 */;
				} else /* pos 104:128 */ {
					echo '-';
				}
				echo '</td>
                                <td class="px-4 py-3 min-w-[220px]">
';
				$docJson = json_encode($doc, 128) /* pos 106:37 */;
				echo '                                    <button
                                        type="button"
                                        class="mb-2 rounded border border-blue-500/40 bg-blue-500/10 px-2 py-1 text-xs text-blue-300 hover:bg-blue-500/20"
                                        data-edit-document';
				echo LR\HtmlHelpers::formatDataAttribute('
                                        data-document-id', $doc['_id'] ?? '') /* pos 111:60 */;
				echo LR\HtmlHelpers::formatDataAttribute('
                                        data-document-json', $docJson) /* pos 112:62 */;
				echo '
                                    >
                                        Edit JSON
                                    </button>
                                    <form method="post" action="/documents/';
				echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 116:76 */;
				echo '/delete">
                                        ';
				echo ($this->global->fn->csrf_field)($this, ) /* pos 117:41 */;
				echo '
                                        <input type="hidden" name="db"';
				echo LR\HtmlHelpers::formatAttribute(' value', $dbName) /* pos 118:80 */;
				echo '>
                                        <input type="hidden" name="document_id"';
				echo LR\HtmlHelpers::formatAttribute(' value', $doc['_id'] ?? '') /* pos 119:89 */;
				echo '>
                                        <button class="rounded bg-red-600 px-2 py-1 text-xs">Delete</button>
                                    </form>
                                </td>
                            </tr>
';

			}

		}
		echo '                </tbody>
            </table>
        </div>
        <div class="px-4 py-3 border-t border-white/10 flex justify-between text-sm">
            <span>Skip: ';
		echo LR\HtmlHelpers::escapeText($skip) /* pos 130:25 */;
		echo ' • Limit: ';
		echo LR\HtmlHelpers::escapeText($limit) /* pos 130:44 */;
		echo '</span>
            <div class="flex gap-2">
                <a href="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 132:37 */;
		echo '?db=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 132:65 */;
		echo '&skip=';
		echo LR\HtmlHelpers::escapeAttr(max(0, $skip - $limit)) /* pos 132:91 */;
		echo '&limit=';
		echo LR\HtmlHelpers::escapeAttr($limit) /* pos 132:122 */;
		echo '&status=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($status ?? 'active')) /* pos 132:138 */;
		echo '&sort=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($sort ?? '_id_desc')) /* pos 132:176 */;
		echo '&query_json=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($queryJson ?? '')) /* pos 132:220 */;
		echo '" class="rounded border border-white/20 px-2 py-1 hover:bg-white/10">Prev</a>
                <a href="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 133:37 */;
		echo '?db=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($dbName)) /* pos 133:65 */;
		echo '&skip=';
		echo LR\HtmlHelpers::escapeAttr($skip + $limit) /* pos 133:91 */;
		echo '&limit=';
		echo LR\HtmlHelpers::escapeAttr($limit) /* pos 133:114 */;
		echo '&status=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($status ?? 'active')) /* pos 133:130 */;
		echo '&sort=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($sort ?? '_id_desc')) /* pos 133:168 */;
		echo '&query_json=';
		echo LR\HtmlHelpers::escapeAttr(urlencode($queryJson ?? '')) /* pos 133:212 */;
		echo '" class="rounded border border-white/20 px-2 py-1 hover:bg-white/10">Next</a>
            </div>
        </div>
    </section>
</div>

<div id="createDocumentModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/60 p-4">
    <div class="w-full max-w-4xl rounded-xl border border-white/10 bg-slate-900 p-4 max-h-[90vh] overflow-auto">
        <div class="mb-3 flex items-center justify-between">
            <h4 class="font-semibold">Create Document (Schema Form)</h4>
            <button type="button" id="closeCreateModal" class="rounded border border-white/20 px-2 py-1 text-xs">Close</button>
        </div>
        <form method="post" action="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 145:48 */;
		echo '/create" class="space-y-3">
            ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 146:13 */;
		echo '
            <input type="hidden" name="db"';
		echo LR\HtmlHelpers::formatAttribute(' value', $dbName) /* pos 147:52 */;
		echo '>
';
		if (empty($schemaFields)) /* pos 148:13 */ {
			echo '                <textarea name="document_json" rows="8" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono">{"name":"example"}</textarea>
';
		} else /* pos 150:13 */ {
			echo '                <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
';
			foreach ($schemaFields as $field) /* pos 152:21 */ {
				echo '                        <div>
                            <label class="text-xs text-gray-400">';
				echo LR\HtmlHelpers::escapeText($field['name']) /* pos 154:66 */;
				echo ' (';
				echo LR\HtmlHelpers::escapeText($field['type']) /* pos 154:84 */;
				echo ') ';
				if (!empty($field['required'])) /* pos 154:102 */ {
					echo '<span class="text-red-300">*</span>';
				}
				echo '</label>
';
				if (($field['type'] ?? '') === 'boolean') /* pos 155:29 */ {
					echo '                                <select name="field_';
					echo LR\HtmlHelpers::escapeAttr($field['name']) /* pos 156:53 */;
					echo '" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                                    <option value="">--</option>
                                    <option value="true">true</option>
                                    <option value="false">false</option>
                                </select>
';
				} elseif (($field['type'] ?? '') === 'enum' && !empty($field['enum'])) /* pos 161:29 */ {
					echo '                                <select name="field_';
					echo LR\HtmlHelpers::escapeAttr($field['name']) /* pos 162:53 */;
					echo '" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
                                    <option value="">--</option>
';
					foreach ($field['enum'] as $opt) /* pos 164:37 */ {
						echo '                                        <option';
						echo LR\HtmlHelpers::formatAttribute(' value', $opt) /* pos 165:57 */;
						echo '>';
						echo LR\HtmlHelpers::escapeText($opt) /* pos 165:64 */;
						echo '</option>
';

					}

					echo '                                </select>
';
				} elseif (in_array($field['type'] ?? '', ['array', 'object', 'json'], true)) /* pos 168:29 */ {
					echo '                                <textarea name="field_';
					echo LR\HtmlHelpers::escapeAttr($field['name']) /* pos 169:55 */;
					echo '" rows="3" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono" placeholder=\'{"key":"value"}\'></textarea>
';
				} else /* pos 170:29 */ {
					echo '                                <input name="field_';
					echo LR\HtmlHelpers::escapeAttr($field['name']) /* pos 171:52 */;
					echo '" class="mt-1 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
';
				}


				echo '                        </div>
';

			}

			echo '                </div>
                <details class="mt-2 rounded-lg border border-white/10 bg-white/5 p-2">
                    <summary class="cursor-pointer text-xs text-gray-300">Advanced: raw JSON override</summary>
                    <textarea name="document_json" rows="6" class="mt-2 w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono" placeholder=\'Kosongkan jika pakai form schema\'></textarea>
                </details>
';
		}
		echo '            <div class="flex justify-end gap-2">
                <button type="button" id="cancelCreateModal" class="rounded-lg border border-white/20 px-3 py-2 text-sm">Cancel</button>
                <button class="rounded-lg bg-emerald-600 px-3 py-2 text-sm">Insert</button>
            </div>
        </form>
    </div>
</div>

<div id="editDocumentModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-black/60 p-4">
    <div class="w-full max-w-3xl rounded-xl border border-white/10 bg-slate-900 p-4 max-h-[90vh] overflow-auto">
        <div class="mb-3 flex items-center justify-between">
            <h4 class="font-semibold">Edit Document JSON</h4>
            <button type="button" id="closeEditModal" class="rounded border border-white/20 px-2 py-1 text-xs">Close</button>
        </div>
        <form method="post" action="/documents/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($collection)) /* pos 195:48 */;
		echo '/update" class="space-y-3">
            ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 196:13 */;
		echo '
            <input type="hidden" name="db"';
		echo LR\HtmlHelpers::formatAttribute(' value', $dbName) /* pos 197:52 */;
		echo '>
            <input type="hidden" name="document_id" id="editDocumentId" value="">
            <textarea name="document_json" id="editDocumentJson" rows="14" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono"></textarea>
            <div class="flex justify-end gap-2">
                <button type="button" id="cancelEditModal" class="rounded-lg border border-white/20 px-3 py-2 text-sm">Cancel</button>
                <button class="rounded-lg bg-blue-600 px-3 py-2 text-sm">Save Update</button>
            </div>
        </form>
    </div>
</div>
';
	}


	/** {block scripts} on line 209 */
	public function blockScripts(array $ʟ_args): void
	{
		echo '<script>
(() => {
    const modal = document.getElementById(\'createDocumentModal\');
    const openBtn = document.getElementById(\'openCreateModal\');
    const closeBtn = document.getElementById(\'closeCreateModal\');
    const cancelBtn = document.getElementById(\'cancelCreateModal\');
    if (!modal || !openBtn || !closeBtn || !cancelBtn) return;

    const open = () => {
        modal.classList.remove(\'hidden\');
        modal.classList.add(\'flex\');
    };
    const close = () => {
        modal.classList.add(\'hidden\');
        modal.classList.remove(\'flex\');
    };

    openBtn.addEventListener(\'click\', open);
    closeBtn.addEventListener(\'click\', close);
    cancelBtn.addEventListener(\'click\', close);
    modal.addEventListener(\'click\', (e) => {
        if (e.target === modal) close();
    });

    const editModal = document.getElementById(\'editDocumentModal\');
    const closeEditBtn = document.getElementById(\'closeEditModal\');
    const cancelEditBtn = document.getElementById(\'cancelEditModal\');
    const editIdInput = document.getElementById(\'editDocumentId\');
    const editJsonInput = document.getElementById(\'editDocumentJson\');

    if (!editModal || !closeEditBtn || !cancelEditBtn || !editIdInput || !editJsonInput) return;

    const openEdit = (id, json) => {
        editIdInput.value = id || \'\';
        editJsonInput.value = json || \'{}\';
        editModal.classList.remove(\'hidden\');
        editModal.classList.add(\'flex\');
    };
    const closeEdit = () => {
        editModal.classList.add(\'hidden\');
        editModal.classList.remove(\'flex\');
    };

    document.querySelectorAll(\'[data-edit-document]\').forEach((btn) => {
        btn.addEventListener(\'click\', () => {
            openEdit(btn.getAttribute(\'data-document-id\'), btn.getAttribute(\'data-document-json\'));
        });
    });

    closeEditBtn.addEventListener(\'click\', closeEdit);
    cancelEditBtn.addEventListener(\'click\', closeEdit);
    editModal.addEventListener(\'click\', (e) => {
        if (e.target === editModal) closeEdit();
    });
})();
</script>
';
	}
}
