<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: layouts\auth.latte */
final class Template_d6cce45e21 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="id" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>';
		echo LR\HtmlHelpers::escapeText($pageTitle ?? $title ?? $appName) /* pos 6:12 */;
		echo ' - BangronDB Admin</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <script>
        tailwind.config = { darkMode: \'class\', theme: { extend: { fontFamily: { sans: [\'Inter\', \'sans-serif\'] }, colors: { dark: { 800: \'#1e293b\', 900: \'#0f172a\', 950: \'#020617\' } } } } }
    </script>
    <style>
        body { font-family: \'Inter\', sans-serif; }
    </style>
</head>
<body class="bg-slate-900 text-slate-100 min-h-screen flex items-center justify-center p-4">
    <div class="fixed inset-0 overflow-hidden pointer-events-none">
        <div class="absolute top-1/4 left-1/4 w-96 h-96 bg-indigo-500/10 rounded-full blur-3xl"></div>
        <div class="absolute bottom-1/4 right-1/4 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl"></div>
        <div class="absolute inset-0 opacity-[0.02]" style="background-image: linear-gradient(rgba(255,255,255,.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.1) 1px, transparent 1px); background-size: 50px 50px;"></div>
    </div>

    <div class="w-full max-w-md">
        <div class="text-center mb-8">
            <div class="w-20 h-20 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center mx-auto mb-4 shadow-lg shadow-indigo-500/25">
                <i data-lucide="database" class="w-10 h-10 text-white"></i>
            </div>
            <h1 class="text-3xl font-bold">BangronDB Studio</h1>
            <p class="text-slate-400 mt-2">Database Management Console</p>
        </div>

';
		if ($msg = ($this->global->fn->flash)($this, 'error')) /* pos 33:9 */ {
			echo '            <div class="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-sm">';
			echo LR\HtmlHelpers::escapeText($msg) /* pos 34:99 */;
			echo '</div>
';
		}
		if ($msg = ($this->global->fn->flash)($this, 'success')) /* pos 36:9 */ {
			echo '            <div class="mb-4 rounded-lg border border-green-500/40 bg-green-500/10 px-4 py-3 text-sm">';
			echo LR\HtmlHelpers::escapeText($msg) /* pos 37:103 */;
			echo '</div>
';
		}
		echo '
        <div class="rounded-2xl p-8 shadow-2xl border border-slate-700/50 bg-slate-800/90 backdrop-blur-xl">
';
		$this->renderBlock('content', get_defined_vars()) /* pos 41:13 */;
		echo '        </div>
    </div>
    <script>lucide.createIcons();</script>
</body>
</html>
';
	}


	/** {block content} on line 41 */
	public function blockContent(array $ʟ_args): void
	{
	}
}
