<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: layouts\main.latte */
final class Template_0200ddaec0 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent', 'scripts' => 'blockScripts'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="id" class="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>';
		echo LR\HtmlHelpers::escapeText($pageTitle ?? $title ?? $appName) /* pos 6:12 */;
		echo ' - BangronDB Admin</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/lucide@latest"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
<style>
        @import url(\'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap\');

        body {
            font-family: \'Inter\', sans-serif;
        }

        .sidebar-item.active {
            background: linear-gradient(90deg, rgba(99, 102, 241, 0.2) 0%, transparent 100%);
            border-left: 3px solid #6366f1;
        }

        .glass {
            background: rgba(255, 255, 255, 0.05);
            backdrop-filter: blur(10px);
        }

        .glow {
            box-shadow: 0 0 20px rgba(99, 102, 241, 0.3);
        }

        .scrollbar-thin::-webkit-scrollbar {
            width: 6px;
        }

        .scrollbar-thin::-webkit-scrollbar-track {
            background: #1e1e2e;
        }

        .scrollbar-thin::-webkit-scrollbar-thumb {
            background: #4c4c6d;
            border-radius: 3px;
        }

        .fade-in {
            animation: fadeIn 0.3s ease-in-out;
        }

        @keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(10px);
            }

            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .pulse-dot {
            animation: pulse 2s infinite;
        }

        @keyframes pulse {

            0%,
            100% {
                opacity: 1;
            }

            50% {
                opacity: 0.5;
            }
        }

        .toast-success {
            animation: slideIn 0.3s ease-out;
        }

        .toast-error {
            animation: slideIn 0.3s ease-out;
            background: #ef4444 !important;
        }

        @keyframes slideIn {
            from {
                transform: translateX(100%);
                opacity: 0;
            }

            to {
                transform: translateX(0);
                opacity: 1;
            }
        }

        @keyframes shake {

            0%,
            100% {
                transform: translateX(0);
            }

            10%,
            30%,
            50%,
            70%,
            90% {
                transform: translateX(-5px);
            }

            20%,
            40%,
            60%,
            80% {
                transform: translateX(5px);
            }
        }

        .animate-shake {
            animation: shake 0.5s ease-in-out;
        }

        .toast-info {
            animation: slideIn 0.3s ease-out;
            background: #3b82f6 !important;
        }
    </style>

</head>
<body class="bg-slate-900 text-slate-100 min-h-screen">
';
		$displayUser = $user ?? $currentUser ?? ['name' => 'Admin', 'email' => 'admin@example.com'] /* pos 152:5 */;
		echo '
    <aside class="fixed left-0 top-0 h-full w-64 bg-slate-800 border-r border-slate-700 z-50">
        <div class="p-4 border-b border-slate-700">
            <div class="flex items-center gap-3">
                <div class="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-600 rounded-xl flex items-center justify-center">
                    <i data-lucide="database" class="w-5 h-5 text-white"></i>
                </div>
                <div>
                    <h1 class="font-bold text-lg">BangronDB</h1>
                    <p class="text-xs text-slate-400">Studio v1.0</p>
                </div>
            </div>
        </div>

        <nav class="p-4 space-y-1">
            <a href="/dashboard" class="sidebar-item ';
		if (($navActive ?? '') === 'dashboard') /* pos 168:54 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-white">
                <i data-lucide="layout-dashboard" class="w-5 h-5"></i><span>Dashboard</span>
            </a>
            <a href="/databases" class="sidebar-item ';
		if (($navActive ?? '') === 'databases') /* pos 171:54 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                <i data-lucide="database" class="w-5 h-5"></i><span>Databases</span>
            </a>
            <a href="/query-playground" class="sidebar-item ';
		if (($navActive ?? '') === 'query') /* pos 174:61 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                <i data-lucide="terminal" class="w-5 h-5"></i><span>Query Playground</span>
            </a>
            <a href="/audit" class="sidebar-item ';
		if (($navActive ?? '') === 'audit') /* pos 177:50 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                <i data-lucide="activity" class="w-5 h-5"></i><span>Audit</span>
            </a>
            <a href="/monitoring" class="sidebar-item ';
		if (($navActive ?? '') === 'monitoring') /* pos 180:55 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                <i data-lucide="line-chart" class="w-5 h-5"></i><span>Monitoring</span>
            </a>
            <a href="/security" class="sidebar-item ';
		if (($navActive ?? '') === 'security') /* pos 183:53 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                <i data-lucide="shield" class="w-5 h-5"></i><span>Security</span>
            </a>

            <div class="pt-4 mt-4 border-t border-slate-700">
                <p class="px-4 text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">System</p>
                <a href="/users" class="sidebar-item ';
		if (($navActive ?? '') === 'users') /* pos 189:54 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                    <i data-lucide="users" class="w-5 h-5"></i><span>Users</span>
                </a>
                <a href="/roles" class="sidebar-item ';
		if (($navActive ?? '') === 'roles') /* pos 192:54 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                    <i data-lucide="shield-check" class="w-5 h-5"></i><span>Roles</span>
                </a>
                <a href="/notifications" class="sidebar-item ';
		if (($navActive ?? '') === 'notifications') /* pos 195:62 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                    <i data-lucide="bell" class="w-5 h-5"></i><span>Notifications</span>
                </a>
                <a href="/settings" class="sidebar-item ';
		if (($navActive ?? '') === 'settings') /* pos 198:57 */ {
			echo 'active';
		}
		echo ' flex items-center gap-3 px-4 py-3 rounded-lg text-gray-300 hover:text-white">
                    <i data-lucide="settings" class="w-5 h-5"></i><span>Settings</span>
                </a>
            </div>
        </nav>

        <div class="absolute bottom-0 left-0 right-0 p-4 border-t border-slate-700">
            <div class="flex items-center gap-3">
                <div class="w-10 h-10 bg-gradient-to-br from-green-500 to-emerald-600 rounded-full flex items-center justify-center text-sm font-bold">
                    ';
		echo LR\HtmlHelpers::escapeText(strtoupper(substr((string) ($displayUser['name'] ?? 'A'), 0, 2))) /* pos 207:21 */;
		echo '
                </div>
                <div class="flex-1">
                    <p class="text-sm font-medium">';
		echo LR\HtmlHelpers::escapeText($displayUser['name'] ?? 'Admin') /* pos 210:52 */;
		echo '</p>
                    <p class="text-xs text-slate-400">';
		echo LR\HtmlHelpers::escapeText($displayUser['email'] ?? '-') /* pos 211:55 */;
		echo '</p>
                </div>
                <form method="post" action="/logout">
                    ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 214:21 */;
		echo '
                    <button class="p-2 hover:bg-white/10 rounded-lg transition-colors" title="Logout" type="submit">
                        <i data-lucide="log-out" class="w-4 h-4 text-gray-400"></i>
                    </button>
                </form>
            </div>
        </div>
    </aside>

    <div class="ml-64 min-h-screen">
        <header class="bg-slate-800 border-b border-slate-700 sticky top-0 z-40 px-6 py-4">
            <div class="flex items-center justify-between">
                <div>
                    <h2 class="text-xl font-semibold">';
		echo LR\HtmlHelpers::escapeText($pageTitle ?? $title ?? 'Dashboard') /* pos 227:55 */;
		echo '</h2>
                    <p class="text-sm text-slate-400">';
		echo LR\HtmlHelpers::escapeText($pageSubtitle ?? '') /* pos 228:55 */;
		echo '</p>
                </div>
                <div class="flex items-center gap-3">
                    <div class="relative hidden md:block">
                        <i data-lucide="search" class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"></i>
                        <input type="text" placeholder="Search..." class="pl-10 pr-4 py-2 bg-slate-700 border border-slate-600 rounded-lg text-sm focus:outline-none focus:border-indigo-500 w-64">
                    </div>
                    <button class="relative p-2 hover:bg-slate-700 rounded-lg transition-colors">
                        <i data-lucide="bell" class="w-5 h-5"></i>
                        <span class="absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full"></span>
                    </button>
                </div>
            </div>
        </header>

        <main class="p-6">
';
		if ($msg = ($this->global->fn->flash)($this, 'error')) /* pos 244:13 */ {
			echo '                <div class="mb-4 rounded-lg border border-red-500/40 bg-red-500/10 px-4 py-3 text-sm">';
			echo LR\HtmlHelpers::escapeText($msg) /* pos 245:103 */;
			echo '</div>
';
		}
		if ($msg = ($this->global->fn->flash)($this, 'success')) /* pos 247:13 */ {
			echo '                <div class="mb-4 rounded-lg border border-green-500/40 bg-green-500/10 px-4 py-3 text-sm">';
			echo LR\HtmlHelpers::escapeText($msg) /* pos 248:107 */;
			echo '</div>
';
		}
		$this->renderBlock('content', get_defined_vars()) /* pos 250:13 */;
		echo '        </main>
    </div>

    <script>lucide.createIcons();</script>
';
		$this->renderBlock('scripts', get_defined_vars()) /* pos 255:5 */;
		echo '</body>
</html>
';
	}


	/** {block content} on line 250 */
	public function blockContent(array $ʟ_args): void
	{
	}


	/** {block scripts} on line 255 */
	public function blockScripts(array $ʟ_args): void
	{
	}
}
