<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: monitoring/index.latte */
final class Template_6736ccecd5 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['a' => '29'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$health = is_array($healthStatus ?? null) ? $healthStatus : ['status' => (string) ($healthStatus ?? 'unknown'), 'overall' => 0] /* pos 4:1 */;
		echo '<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-6">
    <div class="glass-card rounded-xl p-6"><p class="text-gray-400 text-sm">CPU Usage</p><p class="text-3xl font-bold mt-2">';
		echo LR\HtmlHelpers::escapeText($systemMetrics['cpu_usage'] ?? 0) /* pos 6:125 */;
		echo '%</p></div>
    <div class="glass-card rounded-xl p-6"><p class="text-gray-400 text-sm">Memory</p><p class="text-3xl font-bold mt-2">';
		echo LR\HtmlHelpers::escapeText($systemMetrics['memory_usage'] ?? 0) /* pos 7:122 */;
		echo '%</p></div>
    <div class="glass-card rounded-xl p-6"><p class="text-gray-400 text-sm">Disk</p><p class="text-3xl font-bold mt-2">';
		echo LR\HtmlHelpers::escapeText($systemMetrics['disk_usage'] ?? 0) /* pos 8:120 */;
		echo '%</p></div>
    <div class="glass-card rounded-xl p-6"><p class="text-gray-400 text-sm">Connections</p><p class="text-3xl font-bold mt-2">';
		echo LR\HtmlHelpers::escapeText($databaseMetrics['connection_count'] ?? 0) /* pos 9:127 */;
		echo '</p></div>
</div>

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
    <section class="lg:col-span-2 glass-card rounded-xl p-5">
        <h3 class="font-semibold text-lg mb-3">Health Summary</h3>
        <div class="space-y-2 text-sm">
            <p>Status: <span class="font-medium">';
		echo LR\HtmlHelpers::escapeText($health['status'] ?? 'unknown') /* pos 16:50 */;
		echo '</span></p>
            <p>Overall Score: <span class="font-medium">';
		echo LR\HtmlHelpers::escapeText($health['overall'] ?? 0) /* pos 17:57 */;
		echo '</span></p>
            <p>Database Page Count: <span class="font-medium">';
		echo LR\HtmlHelpers::escapeText($databaseMetrics['page_count'] ?? 0) /* pos 18:63 */;
		echo '</span></p>
            <p>Cache Hit Rate: <span class="font-medium">';
		echo LR\HtmlHelpers::escapeText($databaseMetrics['cache_hit_rate'] ?? 0) /* pos 19:58 */;
		echo '%</span></p>
        </div>
    </section>

    <section class="glass-card rounded-xl p-5">
        <h3 class="font-semibold text-lg mb-3">Active Alerts</h3>
';
		if (empty($alerts)) /* pos 25:9 */ {
			echo '            <p class="text-sm text-gray-400">No active alerts.</p>
';
		} else /* pos 27:9 */ {
			echo '            <div class="space-y-2">
';
			foreach ($alerts as $a) /* pos 29:17 */ {
				echo '                    <div class="rounded-lg border border-white/10 px-3 py-2">
                        <p class="text-sm">';
				echo LR\HtmlHelpers::escapeText($a['message'] ?? '-') /* pos 31:44 */;
				echo '</p>
                        <p class="text-xs text-gray-400">';
				echo LR\HtmlHelpers::escapeText($a['timestamp'] ?? '-') /* pos 32:58 */;
				echo '</p>
                    </div>
';

			}

			echo '            </div>
';
		}
		echo '    </section>
</div>
';
	}
}
