<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: query-playground/index.latte */
final class Template_c156443994 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['item' => '24'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <section class="rounded-xl border border-white/10 bg-white/5 p-4">
        <h3 class="font-semibold mb-3">Run Query</h3>
        <form method="post" action="/query/run" class="space-y-3">
            ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 8:13 */;
		echo '
            <input name="db"';
		echo LR\HtmlHelpers::formatAttribute(' value', $dbName ?? '') /* pos 9:38 */;
		echo ' placeholder="Database" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" required>
            <input name="collection"';
		echo LR\HtmlHelpers::formatAttribute(' value', $collection ?? '') /* pos 10:46 */;
		echo ' placeholder="Collection" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" required>
            <label class="text-xs text-gray-400">Criteria JSON</label>
            <textarea name="criteria_json" rows="5" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono">';
		echo LR\HtmlHelpers::escapeText($criteriaJson ?? '{}') /* pos 12:141 */;
		echo '</textarea>
            <label class="text-xs text-gray-400">Sort JSON</label>
            <textarea name="sort_json" rows="3" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono">';
		echo LR\HtmlHelpers::escapeText($sortJson ?? '{"_id":-1}') /* pos 14:137 */;
		echo '</textarea>
            <input type="number" name="limit"';
		echo LR\HtmlHelpers::formatAttribute(' value', $limit ?? 50) /* pos 15:55 */;
		echo ' min="1" max="200" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
            <button class="rounded-lg bg-blue-600 px-4 py-2 text-sm">Run</button>
        </form>
    </section>

    <section class="rounded-xl border border-white/10 bg-white/5 p-4">
        <h3 class="font-semibold mb-3">History</h3>
';
		if (empty($history)) /* pos 22:9 */ {
			echo '        <p class="text-sm text-gray-400">No history.</p>';
		} else /* pos 22:77 */ {
			echo '
            <div class="space-y-2">
';
			foreach ($history as $item) /* pos 24:17 */ {
				echo '                    <div class="rounded-lg border border-white/10 px-3 py-2">
                        <p class="text-xs font-mono">';
				echo LR\HtmlHelpers::escapeText($item['payload']['db'] ?? '-') /* pos 26:54 */;
				echo ' / ';
				echo LR\HtmlHelpers::escapeText($item['payload']['collection'] ?? '-') /* pos 26:88 */;
				echo '</p>
                        <p class="text-xs text-gray-400">';
				echo LR\HtmlHelpers::escapeText($item['created_at'] ?? '-') /* pos 27:58 */;
				echo '</p>
                    </div>
';

			}

			echo '            </div>
';
		}
		echo '    </section>
</div>

<section class="rounded-xl border border-white/10 bg-white/5 p-4 mt-6">
    <h3 class="font-semibold mb-3">Results</h3>
';
		if (empty($results)) /* pos 37:5 */ {
			echo '        <p class="text-sm text-gray-400">No result yet.</p>
';
		} else /* pos 39:5 */ {
			echo '        <pre class="text-xs whitespace-pre-wrap break-all">';
			echo LR\HtmlHelpers::escapeText(json_encode($results, 128)) /* pos 40:60 */;
			echo '</pre>
';
		}
		echo '</section>
';
	}
}
