<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: roles/permissions.latte */
final class Template_4cdb0bff8d extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['perm' => '7'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="rounded-xl border border-white/10 bg-white/5 p-4">
<h3 class="font-semibold mb-3">Role Permissions</h3>
<form method="post" action="/roles/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($role['_id'] ?? $role['id'] ?? '')) /* pos 5:36 */;
		echo '/permissions" class="space-y-3">
';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 6:1 */;
		echo "\n";
		foreach ($allPermissions as $perm) /* pos 7:1 */ {
			echo '<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="permissions[]"';
			echo LR\HtmlHelpers::formatAttribute(' value', $perm['key'] ?? $perm['_id'] ?? '') /* pos 8:100 */;
			echo ' ';
			if (in_array($perm['key'] ?? $perm['_id'] ?? '', $rolePermissions ?? [])) /* pos 8:137 */ {
				echo 'checked';
			}
			echo '> ';
			echo LR\HtmlHelpers::escapeText($perm['key'] ?? $perm['_id'] ?? '') /* pos 8:226 */;
			echo '</label>
';

		}

		echo '<button class="rounded-lg bg-blue-600 px-4 py-2 text-sm">Save</button>
</form>
</div>
';
	}
}
