<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: roles/create.latte */
final class Template_5017e1381a extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="max-w-2xl rounded-xl border border-white/10 bg-white/5 p-4">
<h3 class="font-semibold mb-3">Create Role</h3>
<form method="post" action="/roles/create" class="space-y-3">
';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 6:1 */;
		echo '
<input name="name" required placeholder="Role name" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<input name="description" placeholder="Description" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<button class="rounded-lg bg-blue-600 px-4 py-2 text-sm">Save</button>
</form>
</div>
';
	}
}
