<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: roles/index.latte */
final class Template_72cf472f3a extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['r' => '10'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="flex items-center justify-between mb-6">
    <h3 class="text-lg font-semibold">Roles</h3>
    <a href="/roles/create" class="rounded-lg bg-blue-600 px-3 py-2 text-sm">Create Role</a>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
';
		foreach ($roles as $r) /* pos 10:5 */ {
			echo '        <article class="glass-card rounded-xl p-4">
            <h4 class="font-semibold">';
			echo LR\HtmlHelpers::escapeText($r['name'] ?? $r['_id'] ?? '') /* pos 12:39 */;
			echo '</h4>
            <p class="text-sm text-gray-400 mt-1">';
			echo LR\HtmlHelpers::escapeText($r['description'] ?? '-') /* pos 13:51 */;
			echo '</p>
            <div class="mt-4 flex gap-2 text-xs">
                <a href="/roles/';
			echo LR\HtmlHelpers::escapeAttr(urlencode($r['_id'] ?? '')) /* pos 15:33 */;
			echo '" class="text-blue-400">View</a>
                <a href="/roles/';
			echo LR\HtmlHelpers::escapeAttr(urlencode($r['_id'] ?? '')) /* pos 16:33 */;
			echo '/edit" class="text-purple-300">Edit</a>
                <a href="/roles/';
			echo LR\HtmlHelpers::escapeAttr(urlencode($r['_id'] ?? '')) /* pos 17:33 */;
			echo '/permissions" class="text-amber-300">Permissions</a>
            </div>
        </article>
';

		}

		echo '</div>
';
	}
}
