<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: roles/show.latte */
final class Template_5409d0a718 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="rounded-xl border border-white/10 bg-white/5 p-4 space-y-2">
<h3 class="font-semibold">Role Detail</h3>
<p><span class="text-gray-400">Name:</span> ';
		echo LR\HtmlHelpers::escapeText($role['name'] ?? '-') /* pos 5:45 */;
		echo '</p>
<p><span class="text-gray-400">Description:</span> ';
		echo LR\HtmlHelpers::escapeText($role['description'] ?? '-') /* pos 6:52 */;
		echo '</p>
<a href="/roles/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($role['_id'] ?? $role['id'] ?? '')) /* pos 7:17 */;
		echo '/edit" class="inline-block rounded-lg border border-white/20 px-3 py-2 text-sm">Edit</a>
</div>
';
	}
}
