<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: security/index.latte */
final class Template_ac4223e443 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <section class="glass-card rounded-xl p-5">
        <h3 class="font-semibold text-lg mb-3">Security Status</h3>
        <p class="text-sm mb-1">Active key: ';
		if (!empty($status['has_active_key'])) /* pos 7:45 */ {
			echo 'Yes';
		} else /* pos 7:86 */ {
			echo 'No';
		}
		echo '</p>
        <p class="text-sm mb-4">Policies: ';
		echo LR\HtmlHelpers::escapeText($status['policies'] ?? 0) /* pos 8:43 */;
		echo '</p>
        <form method="post" action="/security/key/rotate">
            ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 10:13 */;
		echo '
            <button class="rounded-lg bg-amber-600 hover:bg-amber-700 px-4 py-2 text-sm">Rotate Key</button>
        </form>
    </section>

    <section class="glass-card rounded-xl p-5">
        <h3 class="font-semibold text-lg mb-3">Save Policy</h3>
        <form method="post" action="/security/policy/save" class="space-y-3">
            ';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 18:13 */;
		echo '
            <input name="name" required class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm" placeholder="policy_name">
            <textarea name="rules_json" rows="8" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-mono" placeholder=\'{"allow":["document.read"]}\'></textarea>
            <button class="rounded-lg bg-blue-600 hover:bg-blue-700 px-4 py-2 text-sm">Save</button>
        </form>
    </section>
</div>
';
	}
}
