<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: studio/notifications.latte */
final class Template_8f833f2b06 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['n' => '9'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="rounded-xl border border-white/10 bg-white/5 p-4">
<h3 class="font-semibold mb-3">Notifications</h3>
';
		if (empty($items)) /* pos 5:1 */ {
			echo '<p class="text-sm text-gray-400">No notifications.</p>
';
		} else /* pos 7:1 */ {
			echo '<div class="space-y-2">
';
			foreach ($items as $n) /* pos 9:1 */ {
				echo '<div class="rounded-lg border border-white/10 px-3 py-2">
<p class="text-sm font-medium">';
				echo LR\HtmlHelpers::escapeText($n['title'] ?? '-') /* pos 11:32 */;
				echo '</p>
<p class="text-xs text-gray-400">';
				echo LR\HtmlHelpers::escapeText($n['message'] ?? '-') /* pos 12:34 */;
				echo '</p>
<p class="text-xs text-gray-500">';
				echo LR\HtmlHelpers::escapeText($n['created_at'] ?? '-') /* pos 13:34 */;
				echo '</p>
</div>
';

			}

			echo '</div>
';
		}
		echo '</div>
';
	}
}
