<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: studio/settings.latte */
final class Template_1e380ad57f extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="rounded-xl border border-white/10 bg-white/5 p-4">
<h3 class="font-semibold mb-3">System Settings</h3>
';
		if (empty($settings)) /* pos 5:1 */ {
			echo '<p class="text-sm text-gray-400">No settings found.</p>';
		} else /* pos 5:77 */ {
			echo '<pre class="text-xs whitespace-pre-wrap break-all">';
			echo LR\HtmlHelpers::escapeText(json_encode($settings, 128)) /* pos 5:134 */;
			echo '</pre>';
		}
		echo '
</div>
';
	}
}
