<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: users/create.latte */
final class Template_4984797943 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['r' => '12'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="max-w-2xl rounded-xl border border-white/10 bg-white/5 p-4">
<h3 class="font-semibold mb-3">Create User</h3>
<form method="post" action="/users/create" class="space-y-3">
';
		echo ($this->global->fn->csrf_field)($this, ) /* pos 6:1 */;
		echo '
<input name="first_name" placeholder="First name" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<input name="last_name" placeholder="Last name" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<input name="email" type="email" placeholder="Email" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<input name="username" placeholder="Username" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<input name="password" type="password" placeholder="Password" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">
<select name="role_id" class="w-full rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-sm">';
		foreach ($roles as $r) /* pos 12:102 */ {
			echo '<option';
			echo LR\HtmlHelpers::formatAttribute(' value', $r['_id'] ?? $r['id'] ?? '') /* pos 12:140 */;
			echo '>';
			echo LR\HtmlHelpers::escapeText($r['name'] ?? $r['_id'] ?? '') /* pos 12:170 */;
			echo '</option>';
		}

		echo '</select>
<button class="rounded-lg bg-blue-600 px-4 py-2 text-sm">Save</button>
</form>
</div>
';
	}
}
