<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: users/show.latte */
final class Template_1486fb5516 extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		$this->renderBlock('content', get_defined_vars()) /* pos 2:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 2 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="rounded-xl border border-white/10 bg-white/5 p-4 space-y-3">
<h3 class="font-semibold">User Detail</h3>
<p><span class="text-gray-400">Name:</span> ';
		echo LR\HtmlHelpers::escapeText($target['name'] ?? ($target['first_name'] ?? '') . ' ' . ($target['last_name'] ?? '')) /* pos 5:45 */;
		echo '</p>
<p><span class="text-gray-400">Email:</span> ';
		echo LR\HtmlHelpers::escapeText($target['email'] ?? '-') /* pos 6:46 */;
		echo '</p>
<p><span class="text-gray-400">Role:</span> ';
		echo LR\HtmlHelpers::escapeText($target['role_id'] ?? '-') /* pos 7:45 */;
		echo '</p>
<p><span class="text-gray-400">Status:</span> ';
		echo LR\HtmlHelpers::escapeText($target['status'] ?? '-') /* pos 8:47 */;
		echo '</p>
<a href="/users/';
		echo LR\HtmlHelpers::escapeAttr(urlencode($target['_id'] ?? $target['id'] ?? '')) /* pos 9:17 */;
		echo '/edit" class="inline-block rounded-lg border border-white/20 px-3 py-2 text-sm">Edit</a>
</div>
';
	}
}
