<?php

/** Generated by Latte 3.1.1 */

declare(strict_types=1);

use Latte\Runtime as LR;

/** source: users/index.latte */
final class Template_af82a6201e extends Latte\Runtime\Template
{
	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* pos 3:1 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (array_intersect_key(['u' => '20'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = '../layouts/main.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<div class="flex items-center justify-between mb-6">
    <h3 class="text-lg font-semibold">Users</h3>
    <a href="/users/create" class="rounded-lg bg-blue-600 px-3 py-2 text-sm">Create User</a>
</div>

<div class="glass-card rounded-xl overflow-hidden">
    <table class="w-full text-sm">
        <thead class="bg-white/5 text-gray-300">
            <tr>
                <th class="px-4 py-3 text-left">User</th>
                <th class="px-4 py-3 text-left">Role</th>
                <th class="px-4 py-3 text-left">Status</th>
                <th class="px-4 py-3 text-left">Actions</th>
            </tr>
        </thead>
        <tbody>
';
		foreach ($users as $u) /* pos 20:13 */ {
			echo '                <tr class="border-t border-white/10">
                    <td class="px-4 py-3">
                        <p class="font-medium">';
			echo LR\HtmlHelpers::escapeText($u['name'] ?? ($u['first_name'] ?? '') . ' ' . ($u['last_name'] ?? '')) /* pos 23:48 */;
			echo '</p>
                        <p class="text-xs text-gray-400">';
			echo LR\HtmlHelpers::escapeText($u['email'] ?? '-') /* pos 24:58 */;
			echo '</p>
                    </td>
                    <td class="px-4 py-3">';
			echo LR\HtmlHelpers::escapeText($u['role_id'] ?? '-') /* pos 26:43 */;
			echo '</td>
                    <td class="px-4 py-3"><span class="text-xs px-2 py-1 rounded-md bg-emerald-500/20 text-emerald-300">';
			echo LR\HtmlHelpers::escapeText($u['status'] ?? '-') /* pos 27:121 */;
			echo '</span></td>
                    <td class="px-4 py-3">
                        <div class="flex gap-2 text-xs">
                            <a href="/users/';
			echo LR\HtmlHelpers::escapeAttr(urlencode($u['_id'] ?? '')) /* pos 30:45 */;
			echo '" class="text-blue-400">View</a>
                            <a href="/users/';
			echo LR\HtmlHelpers::escapeAttr(urlencode($u['_id'] ?? '')) /* pos 31:45 */;
			echo '/edit" class="text-purple-300">Edit</a>
                            <a href="/users/';
			echo LR\HtmlHelpers::escapeAttr(urlencode($u['_id'] ?? '')) /* pos 32:45 */;
			echo '/permissions" class="text-amber-300">Perms</a>
                        </div>
                    </td>
                </tr>
';

		}

		echo '        </tbody>
    </table>
</div>
';
	}
}
